let songs = [
    {
        "name": "Bob-omb Battlefield",
        "game": "Super Mario 64",
        "audio": "./audio/supermario64/bobombbattlefield.mp3",
        "image": "https://assets1.ignimgs.com/2019/05/31/mario-64---button-1559263987447.jpg",
        "console": "Nintendo 64",
        "releasedate": "September 29, 1996",
    },
    {
        "name": "Dire Dire Docks",
        "game": "Super Mario 64",
        "audio": "./audio/supermario64/dirediredocks.mp3",
        "image": "https://assets1.ignimgs.com/2019/05/31/mario-64---button-1559263987447.jpg",
        "console": "Nintendo 64",
        "releasedate": "September 29, 1996",
    },
    {
        "name": "File Select",
        "game": "Super Mario 64",
        "audio": "./audio/supermario64/fileselect.mp3",
        "image": "https://assets1.ignimgs.com/2019/05/31/mario-64---button-1559263987447.jpg",
        "console": "Nintendo 64",
        "releasedate": "September 29, 1996",
    },
    {
        "name": "Slider",
        "game": "Super Mario 64",
        "audio": "./audio/supermario64/slider.mp3",
        "image": "https://assets1.ignimgs.com/2019/05/31/mario-64---button-1559263987447.jpg",
        "console": "Nintendo 64",
        "releasedate": "September 29, 1996",
    },
    {
        "name": "Delfino Plaza",
        "game": "Super Mario Sunshine",
        "audio": "./audio/supermariosunshine/delfinoplaza.mp3",
        "image": "",
        "console": "GameCube",
        "releasedate": "August 26, 2002",
    },
    {
        "name": "Overworld Theme",
        "game": "Super Mario Bros.",
        "audio": "./audio/supermariobros/overworldtheme.mp3",
        "image": "https://i.etsystatic.com/19063773/r/il/d9a839/2268081713/il_fullxfull.2268081713_en84.jpg",
        "console": "NES",
        "releasedate": "September 13, 1985",
    },
    {
        "name": "Overworld Theme",
        "game": "Super Mario Bros. 2",
        "audio": "./audio/supermariobros2/overworldtheme.mp3",
        "image": "https://mario.wiki.gallery/images/thumb/e/ea/SMB2_Boxart.png/1200px-SMB2_Boxart.png",
        "console": "NES",
        "releasedate": "October 9, 1988",
    },
    {
        "name": "Overworld Theme",
        "game": "Super Mario Bros. 3",
        "audio": "./audio/supermariobros3/overworldtheme.mp3",
        "image": "https://static.posters.cz/image/750/posters/super-mario-bros-3-nes-cover-i20784.jpg",
        "console": "NES",
        "releasedate": "February 12, 1990",
    },
    {
        "name": "Overworld Theme",
        "game": "Super Mario World",
        "audio": "./audio/supermarioworld/overworldtheme.mp3",
        "image": "https://cdn11.bigcommerce.com/s-nq6l4syi/images/stencil/1280x1280/products/64890/224787/115171-1024__78801.1606910442.jpg?c=2?imbypass=on",
        "console": "SNES",
        "releasedate": "August 23rd, 1991",
    },
    {
        "name": "Overworld Theme",
        "game": "New Super Mario Bros.",
        "audio": "./audio/newsupermariobros/overworldtheme.mp3",
        "image": "https://media.gamestop.com/i/gamestop/10036906",
        "console": "Nintendo DS",
        "releasedate": "August 23rd, 1991",
    }
]